export interface SeedModuleDefinition {
  slug: string;
  name: string;
  description: string;
  category: string;
  sortOrder: number;
}

export const DEFAULT_MODULES: SeedModuleDefinition[] = [
  {
    slug: 'todo-personal',
    name: 'To-do List Personal',
    description: 'Track personal priorities, reminders, and individual follow-ups.',
    category: 'Productivity',
    sortOrder: 1,
  },
  {
    slug: 'todo-group',
    name: 'To-do List Group',
    description: 'Coordinate team tasks, ownership, and shared action items.',
    category: 'Productivity',
    sortOrder: 2,
  },
  {
    slug: 'bulletin-board',
    name: 'Bulletin Board',
    description: 'Publish announcements, alerts, and operational notices.',
    category: 'Communication',
    sortOrder: 3,
  },
  {
    slug: 'calendar',
    name: 'Calendar',
    description: 'Manage schedules with day, week, and month planning views.',
    category: 'Planning',
    sortOrder: 4,
  },
  {
    slug: 'map',
    name: 'Map',
    description: 'Visualize locations, assignments, and routing activity.',
    category: 'Operations',
    sortOrder: 5,
  },
  {
    slug: 'task-list',
    name: 'Task List',
    description: 'Organize operational tasks and monitor completion status.',
    category: 'Operations',
    sortOrder: 6,
  },
  {
    slug: 'personnel',
    name: 'Personnel',
    description: 'Manage team records, workforce details, and assignments.',
    category: 'Workforce',
    sortOrder: 7,
  },
  {
    slug: 'vendors-suppliers',
    name: 'Vendors/Suppliers',
    description: 'Store supplier profiles, contacts, and vendor relationships.',
    category: 'Procurement',
    sortOrder: 8,
  },
  {
    slug: 'communication',
    name: 'Communication',
    description: 'Coordinate internal and operational messaging in one place.',
    category: 'Communication',
    sortOrder: 9,
  },
  {
    slug: 'google-drive-storage',
    name: 'Storage / Google Drive',
    description: 'Access shared files, storage locations, and Drive-linked assets.',
    category: 'Files',
    sortOrder: 10,
  },
  {
    slug: 'radio-zello',
    name: 'Radio/Zello API',
    description: 'Connect dispatch-style voice communication and radio workflows.',
    category: 'Communication',
    sortOrder: 11,
  },
  {
    slug: 'task-log-entry',
    name: 'Task Log - Entry',
    description: 'Record completed work, field updates, and accountability logs.',
    category: 'Operations',
    sortOrder: 12,
  },
  {
    slug: 'notes',
    name: 'Notes',
    description: 'Capture quick notes, observations, and operational context.',
    category: 'Productivity',
    sortOrder: 13,
  },
  {
    slug: 'whatsapp',
    name: 'WhatsApp',
    description: 'Support WhatsApp-linked communication workflows and updates.',
    category: 'Communication',
    sortOrder: 14,
  },
  {
    slug: 'phone',
    name: 'Phone',
    description: 'Track direct calling workflows, contact actions, and call activity.',
    category: 'Communication',
    sortOrder: 15,
  },
  {
    slug: 'file-upload',
    name: 'File Upload',
    description: 'Upload operational documents, forms, images, and evidence files.',
    category: 'Files',
    sortOrder: 16,
  },
  {
    slug: 'ai-chatbot',
    name: 'AI Chatbot',
    description: 'Provide AI-assisted search, drafting, and operational help.',
    category: 'Automation',
    sortOrder: 17,
  },
  {
    slug: 'vehicles',
    name: 'Vehicles',
    description: 'Manage fleet information, assignment, and vehicle oversight.',
    category: 'Fleet',
    sortOrder: 18,
  },
  {
    slug: 'contact-list',
    name: 'Contact List',
    description: 'Maintain operational contacts, teams, and external relationships.',
    category: 'Communication',
    sortOrder: 19,
  },
  {
    slug: 'sops',
    name: 'Access to SOPs',
    description: 'Provide controlled access to standard operating procedures.',
    category: 'Compliance',
    sortOrder: 20,
  },
  {
    slug: 'quotes',
    name: 'Quotes',
    description: 'Prepare and manage customer quotations and pricing drafts.',
    category: 'Sales',
    sortOrder: 21,
  },
  {
    slug: 'accounts',
    name: 'Accounts',
    description: 'Review account records, balances, and commercial relationships.',
    category: 'Finance',
    sortOrder: 22,
  },
  {
    slug: 'products-services',
    name: 'Products/Services',
    description: 'Manage service offerings, product catalogues, and commercial items.',
    category: 'Sales',
    sortOrder: 23,
  },
  {
    slug: 'reports',
    name: 'Reports',
    description: 'Access reporting outputs, exports, and operational summaries.',
    category: 'Insights',
    sortOrder: 24,
  },
  {
    slug: 'filters',
    name: 'Filters',
    description: 'Apply saved views, filtering rules, and custom data slices.',
    category: 'Insights',
    sortOrder: 25,
  },
  {
    slug: 'feedback',
    name: 'Feedback',
    description: 'Collect internal feedback, issues, and improvement requests.',
    category: 'Communication',
    sortOrder: 26,
  },
  {
    slug: 'clock',
    name: 'Clock',
    description: 'Show live working time and shift-aware time tracking context.',
    category: 'Time',
    sortOrder: 27,
  },
  {
    slug: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Track deadlines, timed workflows, and critical operational windows.',
    category: 'Time',
    sortOrder: 28,
  },
  {
    slug: 'kpis',
    name: 'KPIs',
    description: 'Review headline business and operational key performance indicators.',
    category: 'Insights',
    sortOrder: 29,
  },
  {
    slug: 'upcoming-due-dates',
    name: 'Upcoming Due Dates',
    description: 'Monitor important deadlines and items requiring action soon.',
    category: 'Compliance',
    sortOrder: 30,
  },
  {
    slug: 'drivers-license-expiry',
    name: 'Drivers License Expiry',
    description: 'Track driver licensing expiry and renewal deadlines.',
    category: 'Compliance',
    sortOrder: 31,
  },
  {
    slug: 'certificate-expiry',
    name: 'Certificate Expiry',
    description: 'Monitor certificate validity, risk, and renewal schedules.',
    category: 'Compliance',
    sortOrder: 32,
  },
  {
    slug: 'contract-renewal',
    name: 'Contract Renewal',
    description: 'Track contract terms, renewal windows, and upcoming actions.',
    category: 'Compliance',
    sortOrder: 33,
  },
  {
    slug: 'invoices-review',
    name: 'Invoices Submitted / Review',
    description: 'Track invoices submitted and those awaiting finance review.',
    category: 'Finance',
    sortOrder: 34,
  },
  {
    slug: 'sales-metrics',
    name: 'Sales Metrics / KPIs',
    description: 'Monitor sales pipeline, conversion, and commercial performance.',
    category: 'Insights',
    sortOrder: 35,
  },
  {
    slug: 'finance-metrics',
    name: 'Finance Metrics / KPIs',
    description: 'Track financial performance, health, and accounting indicators.',
    category: 'Insights',
    sortOrder: 36,
  },
  {
    slug: 'clock-in-out',
    name: 'Clock-in/out',
    description: 'Capture attendance, shift start and finish, and time punches.',
    category: 'Time',
    sortOrder: 37,
  },
];
